### ISSUE TITLE
Unable To Open Transmutation Tablet

### ISSUE THREAD

**Issue by DonovanDMC** [latvian-dev/ProjectEX#97]
I cannot pinpoint what started it, but every time I try to open a transmutation tablet the game just hangs (with a NullPointerException printed out in the logs). The game never fully crashes, it just hangs.

A snippet of the error is here:
```
[20:10:04] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at net.minecraft.nbt.NBTUtil.func_186860_b(SourceFile:167) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_186857_a(CompoundNBT.java:133) ~[?:?]
	at dev.latvian.mods.projectex.block.entity.LinkBaseBlockEntity.func_230337_a_(LinkBaseBlockEntity.java:36) ~[?:1605.2.0-build.3]
```

and my full log is [here](https://pastebin.com/ag9Jm5sP)

According to my player data file, my emc is `25,567,597,839,595,090`, if that's relevant

I've tried the Transmutation Table, Transmutation Tablet, and Arcane Transmutation Tablet, same issue on each

ProjectE Version: `PE1.0.1B`
Project EX Version: `1605.2.0-build.3`

This has made my world completely unplayable as I can't touch my emc

**Comment by HumanBean06** [comment]
Bump! I am having this exact same problem, only started happening after I learned the Final Star Shard.

**Comment by DonovanDMC** [comment]
> Bump! I am having this exact same problem, only started happening after I learned the Final Star Shard.

That sounds like exactly what I did before this

You might be able to manually unlearn it via editing your player file, I'm going to try that later

**Comment by HumanBean06** [comment]
When you find out how to do that can you lmk? :)

**Comment by DonovanDMC** [comment]
I was able to get the table open long enough to unlearn it via the gui, the manual way can be very time consuming depending on how much you've learned

* Download [NBTExplorer](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac) (this works for Windows, Mac & Linux (via Wine))
* open the "level.dat" (File > Open) file inside of your world folder
* Open (Click the "+" on) Data, Player, ForgeCaps, projecte:knowledge, knowledge
* find the entry that has the item "projectex:final_star_shard"

**Comment by DonovanDMC** [comment]
...and I'm still crashing after having removed it.

**Comment by DonovanDMC** [comment]
I finally removed all the power flowers in my world and search works fine, try unlearning the final star shard & removing all power flowers

last resort completely remove projectEX

**Comment by DonovanDMC** [comment]
Looks like these same issues are becoming a lot more widespread

#106 #107 #108

**Comment by HumanBean06** [comment]
I'm in projecte:knowledge, and the 'knowledge' part has 0 entries. I think it's because the world is not hosted on my computer, and the person hosting doesn't have anything learned with ProjectE. I will try to unlearn it manually, and obliterate all my bonsais.
Thank you very much for finding the solution :)

**Comment by DistantAE** [comment]
Im having similar issues, yet its with the tomb of knowledge.
Does learning it cause the crash? because i can learn the final star shard just fine.

**Comment by DonovanDMC** [comment]
> ...and I'm still crashing after having removed it.
> 
> **Someone needs to pick up this mod and actually care about it, unlike the current dev apparently**
> 
> ~Though it seems like my crashes are random now,~ it isn't crashing immediately after opening my tablet
> 
> Nevermind, it's when I start typing in the search. I have no idea what to do now as there are absolutely no logs saying anything about this

I'm now trying my hand at rewriting this mod from scratch since the current dev doesn't seem to care

I'll put it on curseforge and put a link here whenever I have a workable prototype

**Comment by HumanBean06** [comment]
dev bad pls fix

**Comment by DonovanDMC** [comment]
It's up now, pending on curseforge as I type this but it can be downloaded from github
it's got all of the same things as ProjectEX, minus putting in blocks that are WIP, I plan on trying to implement some of these things over time

https://github.com/DonovanDMC/ProjectExpansion
https://www.curseforge.com/minecraft/mc-mods/project-expansion

**Comment by HumanBean06** [comment]
YOU ARE THE DEFINITION OF LEGEND

Note: ProjectExpansion an official projecte addon so you might wanna change the name

**Comment by DonovanDMC** [comment]
> Note: ProjectExpansion an official projecte addon so you might wanna change the name, though it's probably dead

I don't get what you mean

I've got the notice that it's unofficial to attempt to keep the dev of ProjectE at bay since he clearly has beef with this project (based on #100)

**Comment by DistantAE** [comment]
> hey one last visit around here, I've fixed this exact issue in [v1.0.2](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/v1.0.2) of my fork 👀

Amazing work my good sir.
